version: "3.7"

services:

  graph-api:
    ports:
      - 5101:5101 # listen port
      - 5102:5102 # http port
    environment: 
      - Services__GraphApi__RestUri=http://localhost:5102
      - Services__ProductCatalogService__RestUri=http://product-catalog-api:5202
      - Services__ProductCatalogService__GrpcUri=http://product-catalog-api:5203
      - Services__InventoryService__RestUri=http://inventory-api:5302
      - Services__InventoryService__GrpcUri=http://inventory-api:5303

  product-catalog-api:
    ports:
      - 5201:5201 # listen port
      - 5202:5202 # http port
    environment: 
      - Services__GraphApi__RestUri=http://graph-api:5102
      - DAPR_HTTP_PORT=5202
      - Services__InventoryService__RestUri=http://inventory-api:5302
      - Services__InventoryService__GrpcUri=http://inventory-api:5303

  inventory-api:
    ports:
      - 5301:5301 # listen port
      - 5302:5302 # http port
      - 5303:5303 # grpc port
    environment: 
      - Services__GraphApi__RestUri=http://localhost:5102
      - Services__ProductCatalogService__RestUri=http://product-catalog-api:5202
      - Services__ProductCatalogService__GrpcUri=http://product-catalog-api:5203
      - DAPR_HTTP_PORT=5302
      - DAPR_GRPC_PORT=5303

  sqlserver:
    environment:
      SA_PASSWORD: "P@ssw0rd"
      ACCEPT_EULA: "Y"
    ports:
      - 1433:1433

  redis:
    environment:
      REDIS_PASSWORD: ""
      ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - 6379:6379

  zipkin:
    ports:
      - 9412:9411

  elasticsearch:
    environment:
    - node.name=elasticsearch
    - cluster.name=docker-cluster
    - bootstrap.memory_lock=true
    - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    - discovery.type=single-node
    ports:
    - 9200:9200

  zookeeper:
    ports:
      - 2181:2181

  kafka:
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_CREATE_TOPICS: "test:1:1"
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
    ports:
      - 9092:9092